### ISSUE TITLE
Is this schematic tested on real devices?

### ISSUE THREAD

**Issue by ashumkin** [piwko28/smart-home-ebus-adapter#1]
Hello!
Have you manufactured a PCB and tested it? Does it really work? Also, the SMD version?
I'm looking for alternatives for the components used in the [original schematic ](https://adapter.ebusd.eu/v2/index.en.html) and your schematic LGTM ))

Also, what were the reasons to use parallel and sequential connections of resistors (e.g. R4+R5, R2+R7, R8+R9)?

**Comment by ashumkin** [comment]
any response?

**Comment by bbilas** [comment]
@ashumkin have you already verified that on your own? I also want to order the pcbs so this information would be useful.

**Comment by ashumkin** [comment]
@bbilas, unfortunately, not yet. I hope to do it but with no deadline :)

**Comment by piwko28** [comment]
@ashumkin I've updated the schematics, incl. smd version. It's been tested on many devices and boilers. I'll put there measuring points voltage values and updated housing soon.

Re. sequential connections of resistors: I just had these values in storage, but you can simply use just one with correct value. There are really small currents, so it does not matter.
